### ISSUE TITLE
Migration and env interpolation

### ISSUE THREAD

**Issue by ko10ok** [ko10ok/maxwelld#10]
Interpolation decomposition + tests

Tests for env params injected via `Service(Env(.. params ..))`

Tests for env and migration services interpolation and parametrization
```
services:
  s1:
    envoronment:
      - {s2}=value
    x-migration:
      -after-healthy: make migratioin {s2}-db
      -after-healthy: [[make {s2}], {s3}]
```

```
services:
  s1:
    envoronment:
      - {s2}=value
    x-migration:
      -after-healthy: add topic {s2} in {kafka}

Enviroment( smth_for_intp(kafka='kafka.dev'))
```
